name = "web-archive"
pages_build_output_dir = "./src"
compatibility_flags = [ "nodejs_compat_v2" ]
compatibility_date = "2024-10-21"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "web-archive"

[[d1_databases]]
binding = "DB"
database_name = "web-archive"
database_id = "45fca787-b104-47b1-865d-9dad6e7b0a77"
migrations_dir = './src/sql/migrations'

[ai]
binding = "AI"
